python3 train.py \
        --dataset_name "medmcqa" \
        --n_options 4 \
        --model_size base \
        --per_gpu_batch_size 2 \
        --n_context 5 \
        --name my_test \
        --accumulation_steps 4 \
        --total_steps 72536 \
        --eval_freq 18134 \
        --text_maxlength 512 \
        --warmup_steps 3022